### ISSUE TITLE
Alt-Names option

### ISSUE THREAD

**Issue by costinchirita** [kala13x/flipper-xremote#10]
Is it gone ?
If it's a bug and you fix it can you also make Alt-Names.cfg file into a .txt file so we can adjust it on the go within the phone. Now you can not edit .cfg files, .txt is ok. Thanks

**Comment by costinchirita** [comment]
I mean editing in the flipper app

**Comment by kala13x** [comment]
@costinchirita `Is it gone ?`
what do you mean by that? What is gone?

**Comment by costinchirita** [comment]
Sorry, the Alt_names option

**Comment by costinchirita** [comment]
From what i understood it was supposed to be an option inside Settings to enable or disable it

**Comment by kala13x** [comment]
@costinchirita hmm, are you looking in the app settings? what version do you have?

**Comment by costinchirita** [comment]
1.2.0

**Comment by kala13x** [comment]
@costinchirita It was implemented in 1.3.0. Please check the [changelog](https://github.com/kala13x/flipper-xremote/blob/main/docs/changelog.md)

Also, I just changed the extension from cfg to txt, and the code is already in the main branch. I will close this issue now.
