### ISSUE TITLE
App not building on toolchain 46.0 f7

### ISSUE THREAD

**Issue by doomwastaken** [kala13x/flipper-xremote#5]
Greetings! I am from Flipper Devices team and would like to say thank you for submitting your app to the catalog. We are finalizing API prior to 1.0 release and currently your application cannot be built for latest toolchain. Currently we are testing 0.95.0-rc and app is not being built for that version. 

We are currently working on automating the messages from our build server, so this one is manual :)

If you have any questions, just tag me

**Comment by kala13x** [comment]
@doomwastaken Hi, thanks for opening the issue and for the info.
I will fix it in the next few days and push the change to the app catalog as well.

**Comment by kala13x** [comment]
@doomwastaken Hi, 

I just pushed the request on the flipper app catalog: 
https://github.com/flipperdevices/flipper-application-catalog/pull/202

I will close this issue once the pull request is merged.
