### ISSUE TITLE
Update the XRemote app for the SDK version 0.96 f7

### ISSUE THREAD

**Issue by furippa** [kala13x/flipper-xremote#7]
Hello!

Your XRemote app version `1.1` fails to build with the SDK version `0.96.0-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/6523ee9d624fe737a0dd9ee0/page)

Flipper Team

**Comment by kala13x** [comment]
@furippa 
Hi, thanks for the ticket. I will do it this weekend and then create a new pull request

**Comment by kala13x** [comment]
@furippa I just tried the build with 0.99.1 and it was successful, so is this issue still relevant?

**Comment by doomwastaken** [comment]
Greetings @kala13x that is a bot, sadly we have some issues with its logic, we are working on the fix. Sorry for inconvenience.
