### ISSUE TITLE
Add new button eject

### ISSUE THREAD

**Issue by GrafOrlok** [kala13x/flipper-xremote#8]
Hello,
Can you please add new label in the section control name eject to be use with cd/dvd/bluray players

**Comment by kala13x** [comment]
@GrafOrlok Hi, I did it and merged it to the main branch. I've also made a [pull request](https://github.com/flipperdevices/flipper-application-catalog/pull/311) to the app catalog, and hopefully, the new version will appear in the catalog soon.

In the new version, when learning the remote, the application will also allow you to clone the Eject button, and then Eject can be used by setting it to any button in the custom layout.

**Comment by GrafOrlok** [comment]
Many thanks !!!!
